--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adamMCBE/MinUtill
build-by-default: true
branches:
- main
projects:
  MinUtill:
    path: ""
    model: virion
    type: library
...
